{
  "bad": false,
  "new_version": "2.0.2",
  "new_version_attempt_ts": {
    "2.0.0": 1758387186.0,
    "2.0.1": 1758361986.0,
    "2.0.2": 1759229207
  },
  "new_version_attempts": {
    "1.5.3": 1,
    "1.6.0": 1,
    "1.6.1": 0,
    "1.7.0": 1,
    "2.0.0": 1,
    "2.0.1": 8,
    "2.0.2": 944
  },
  "new_version_errors": {
    "2.0.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12198159764\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name periodictable --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2.0.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n\"",
    "2.0.1": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12422837116\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name periodictable --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2.0.1' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n\"",
    "2.0.2": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/18127005637\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 233, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 270, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 308, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2.0.2' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'\n\n"
  }
}