{
  "bad": false,
  "new_version": "1.2.0",
  "new_version_attempts": {
    "0.3.1": 1,
    "0.4.10": 1,
    "0.4.11": 1,
    "0.4.4": 1,
    "0.4.5": 1,
    "0.4.6": 1,
    "0.4.7": 1,
    "0.4.9": 1,
    "0.5.0": 1,
    "1.0.0": 41,
    "1.2.0": 90
  },
  "new_version_errors": {
    "1.0.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10292319511\">bot CI job</a>): main:\nError running migrate-feedstock in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.0.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/thu-ml/tianshou/releases/download/v{{ version }}/tianshou-{{ version }}.tar.gz'\n\"",
    "1.2.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/16410482169\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 231, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 291, in migrate\n    version = attrs.get(\"version_pr_info\", {}).get(\"new_version\", None)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<frozen _collections_abc>\", line 774, in get\n  File \"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", line 1049, in __getitem__\n    self._load()\n  File \"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", line 1007, in _load\n    data_str = backend.hget(self.hashmap, self.node)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", line 292, in hget\n    r.raise_for_status()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://github.com/regro/cf-graph-countyfair/raw/master/version_pr_info/8/1/0/6/5/tianshou.json\n"
  }
}